Makefile
Bring fetching scripts from controller-runtime to allow test job from https://github.com/openshift/release/pull/14749 to pass.
=> Add etcd fetcher for CI task

cmd/cluster-cloud-controller-manager-operator/main.go, controllers/cache.go, controllers/clusteroperator_controller.go, go.mod, pkg/cloud/aws.go, vendor/modules.txt
Implemented for `Infrastructure` resource.
=> Initial implementation for resource provision with SSA

controllers/clusteroperator_controller.go
Operator is supposed to report release version to be considered healthy.
=> Add release version reporting

cmd/cluster-cloud-controller-manager-operator/main.go, controllers/clusteroperator_controller.go, controllers/clusteroperator_controller_test.go, controllers/suite_test.go, vendor/github.com/onsi/ginkgo/extensions/table/table.go, vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go, vendor/modules.txt
Make sure the `ClusterOperator` is provisioned, have necessary fields populated and marked available even when there is no infrastructure in place to provision.
=> [OCPCLOUD-1089] Simple e2e test suite for CCCMO clusterOperator 

controllers/cache.go
Compare objects on update, while stripping fields which change on no-op
resource update.
Avoiding https://github.com/kubernetes/kubernetes/issues/100024
=> Mitigate hot-loop in SSA

hack/container-run.sh
This change adds a convenience script for wrapping make commands in a
container run.
=> add container-run.sh script

README.md
includes how to build and some status about the operator and supported
platforms.
=> update readme with more instructions

README.md, docs/dev/hacking-guide.md
Describe steps how to build a release payload with multiple operator
changes and deploy a cluster with them.
=> Introduce hacking guide how to build and test features for CCCMO

Makefile
This commit adds lint validations from golangci-lint project. Also it introduces "verify" target, that combines "fmt", "vet" and "lint".
=> Add golangci-lint checks

controllers/cloud_config_sync_controller.go, controllers/cloud_config_sync_controller_test.go, controllers/clusteroperator_controller.go, controllers/clusteroperator_controller_test.go, controllers/common_consts.go, controllers/suite_test.go, controllers/watch_predicates.go
Separate controller for react on changes in cloud-config configmaps in `openshift-config` and `openshift-config-managed` namespaces
=> [OCPCLOUD-1181] Cloud conf sync controller

pkg/cloud/aws/aws.go, pkg/cloud/azure/azure.go, pkg/cloud/cloud.go, pkg/cloud/common/sources.go, pkg/cloud/common/sources_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/controllers/cloud_config_sync_controller_test.go, pkg/controllers/clusteroperator_controller_test.go, pkg/render/render_test.go
This commit fixes formatting and typos.
=> Good ol' cleanup

cmd/cluster-cloud-controller-manager-operator/main.go, manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml, pkg/controllers/cloud_config_sync_controller.go, pkg/controllers/cloud_config_sync_controller_test.go, pkg/controllers/common_consts.go, pkg/controllers/suite_test.go, pkg/controllers/watch_predicates.go
Enable missed cloud-config-sync controller. Forgot to include in in final version of #61. Sorry...
=> Enable cloud-config-sync controller

Makefile, hack/go-get-tool.sh, hack/unit-tests.sh
Enable Junit reports for unit-tests run within OCP CI.
=> Junit report for CI runs

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
This PR sets CCCMO deployment name to cluster-cloud-controller-manager-operator.
=> Rename CCCMO deployment

README.md
=> spell correction of deployed

manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-ibm.yaml, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/ibm/assets/deployment.yaml, pkg/cloud/ibm/ibm.go, pkg/cloud/ibm/ibm_test.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2136
=> Add initial ibm pkg assets and embed files

pkg/controllers/clusteroperator_controller.go
This implementation improves readability of the code by dedicating a specific domain for pre-provision cluster checks.
Co-authored-by: Danil Grigorev <dgrigore@redhat.com>
=> Unify pre-provisioning checks in a single location

pkg/cloud/cloud.go
This PR contains the changes to add Power VS platform in CCCMO
Related to enhancement: https://github.com/openshift/enhancements/pull/736
=> Powervs support

manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml, manifests/0000_26_cloud-controller-manager-operator_16_credentialsrequest-gcp.yaml, manifests/image-references, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/gcp/assets/cloud-controller-manager.yaml, pkg/cloud/gcp/gcp.go, pkg/cloud/gcp/gcp_test.go, pkg/config/config.go
This commit allows to deploy GCP cloud controller manager on OpenShift.
=> Add GCP CCM support

manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml, manifests/0000_26_cloud-controller-manager-operator_16_credentialsrequest-vsphere.yaml, manifests/image-references, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/vsphere/assets/cloud-controller-manager-daemonset.yaml, pkg/cloud/vsphere/assets/cloud-controller-manager-deployment.yaml, pkg/cloud/vsphere/vsphere.go, pkg/cloud/vsphere/vsphere_test.go, pkg/config/config.go
Add bits for deploy ccm on vsphere platform
Successfully migrated OCP cluster on my lab vSphere once.
=> Vsphere ccm support

pkg/controllers/cloud_config_sync_controller_test.go
You should not use gomega assertions within async assertions as was previously done. This meant that the async assertions actually had nothing to assert against. A bug in gomega allowed the tests to pass though they shouldn't have done.
=> Bug 2032926: Fix config sync tests to use async assertions correctly

README.md, manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml, manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-powervs.yaml, manifests/image-references, pkg/cloud/cloud.go, pkg/cloud/powervs/assets/deployment.yaml, pkg/cloud/powervs/powervs.go, pkg/cloud/powervs/powervs_test.go, pkg/config/config.go
This PR contains the changes to add Power VS cloud controller manager
=> Add PowerVS cloud controller manager

pkg/controllers/cloud_config_sync_controller.go, pkg/controllers/cloud_config_sync_controller_test.go
Some of AWS regions might require to sync a cloud-config,
in such case reference in infra resource will be presented.
=> Bug 2104373: Improve decision logic around syncing cloud config

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
This PR sets a default container for the CCCMO.
=> [OCPCLOUD-1708]: Set default container for operator

manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml, manifests/0000_26_cloud-controller-manager-operator_18_credentialsrequest-nutanix.yaml, manifests/image-references, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/nutanix/assets/cloud-controller-manager-deployment.yaml, pkg/cloud/nutanix/nutanix.go, pkg/cloud/nutanix/nutanix_test.go, pkg/config/config.go, pkg/controllers/cloud_config_sync_controller.go
Integrate ccm-nutanix to OCP via CCCMO
=> Integrate ccm-nutanix to OCP via CCCMO

manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml, pkg/cloud/nutanix/assets/cloud-controller-manager-deployment.yaml
- Add rbac permission for Nutanix CCM manager
- Change to the nutanix ccm deployment settings
=> OCPBUGS-8530: add rbac permission for Nutanix CCM manager

pkg/controllers/cloud_config_sync_controller.go, pkg/controllers/clusteroperator_controller.go, pkg/controllers/status.go, pkg/controllers/status_test.go, pkg/controllers/trusted_ca_bundle_controller.go
=> OCPBUGS-15746: Alibaba platforms should not be upgradeable

README.md
this change is being proposed to update the information so that people know this operator is production ready and also to add new provider information.
=> update readme to stable status

manifests/0000_26_cloud-controller-manager-operator_13_credentialsrequest-openstack.yaml, manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml, manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-ibm.yaml, manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-powervs.yaml, manifests/0000_26_cloud-controller-manager-operator_16_credentialsrequest-gcp.yaml, manifests/0000_26_cloud-controller-manager-operator_17_credentialsrequest-vsphere.yaml, manifests/0000_26_cloud-controller-manager-operator_18_credentialsrequest-nutanix.yaml
Add capability annotations to cloud credentials requests
=> OCPVE-788: annotate credentials request manifests

README.md, cmd/cluster-cloud-controller-manager-operator/main.go
Based on https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/307#issuecomment-1849114982
=> trt-1382: reorder flag initialization

.snyk
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!
=> OCPBUGS-25750: Add Snyk file to exclude vendor directory on scan

pkg/cloud/powervs/assets/deployment.yaml
1) Change the --bind-address argument to 127.0.0.1
2) Remove updating the pod IP address
=> OCPBUGS-26494: PowerVS: handle 4.16 changes

.snyk
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!
=> OCPBUGS-25751: Add Snyk file to exclude vendor directory on scan

pkg/controllers/cloud_config_sync_controller_test.go
The matchers used with `Eventually` checks boiled down to a boolean
comparison, which is often unhelpful when debugging. This change uses
more detailed Gomega matchers in order to aid developers making changes.
This explicitly does _not_ try to consolidated the inconsistent import usages of Gomega within this repository.
=> NO-JIRA:Use expressive Gomega matchers with Eventually

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml, pkg/cloud/alibaba/assets/alibaba-cloud-controller-manager-deployment.yaml, pkg/cloud/aws/assets/deployment.yaml, pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml, pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml, pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml, pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml, pkg/cloud/gcp/assets/cloud-controller-manager.yaml, pkg/cloud/ibm/assets/deployment.yaml, pkg/cloud/nutanix/assets/cloud-controller-manager-deployment.yaml, pkg/cloud/openstack/assets/deployment.yaml, pkg/cloud/powervs/assets/deployment.yaml, pkg/cloud/vsphere/assets/cloud-controller-manager-deployment.yaml
All openshift operators must include FallbackToLogsOnError to ease debugging.
=> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml
this change adds some of the linked action permissions that are needed to ensure proper operation.
=> OCPBUGS-44126: update azure permissions

pkg/cloud/cloud_test.go, pkg/cloud/common/resources.go, pkg/controllers/clusteroperator_controller_test.go, pkg/controllers/resourceapply/resourceapply.go
Adds services to expose port 10258 for each provider cloud controller manager.
=> OCPBUGS-53300: Adds service for cloud-controller-manager
