openshift/cluster-cloud-controller-manager-operator

Dockerfile
Makefile
manifests/0000_26_cloud-controller-manager-operator_02_rbac.yaml
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
manifests/image-references

Manifest for image referencing and operator deployment, which will be later populated by CI.
To test image in production here is a temporary operator image location `quay.io/dgrigore/cluster-cloud-controller-manager-operator:latest`.

Operator deployment

---

Dockerfile

`@cluster-bot launch 4.7.0-fc.3,openshift/cluster-cloud-controller-manager-operator#7 aws` should give desired operator in a cluster.

Add label in Dockerfile to include operator in CI release images

---

Dockerfile

This reverts commit 184c512942387c073f676e5bbe74dad3de2b3260, #7.
This is breaking release promotion, with failures [like][1]:
ClusterOperators should define at least one namespace in their lists of related objects
Please don't add yourself to the release image until you have a presubmit running the standard break-the-world e2e suite.
[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-4.8/1359162296110157824

Revert "Add label to include in CI release images"

---

controllers/clusteroperator_controller.go
controllers/clusteroperator_controller_test.go
controllers/suite_test.go

Add a test case for provisioning managed resources. Was tested locally on https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/15, but will later require some changes in the way we configure flags on the deployment. This change although is self sufficient.

[OCPCLOUD-1110] Add e2e tests for managed resources provisioning

---

Dockerfile
controllers/clusteroperator_controller.go

Reverts openshift/cluster-cloud-controller-manager-operator#14 in attempt to add operator back to release.
We should have basic e2e for AWS running now. @wking PTAL

Revert "Revert "Add label to include in CI release images""

---

cmd/cluster-cloud-controller-manager-operator/main.go
controllers/clusteroperator_controller.go
hack/example-images.json
manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
manifests/image-references

Mount config map into `CCCMO` deployment for correct image version
evaluation on operator startup. Images will be dynamically passed to
operand controllers.
To deploy operator locally you now need to specify a command line argument:
```bash
./bin/cluster-controller-manager-operator --images-json=hack/example-images.json
```

Add images config map

---

manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml
pkg/cloud/aws.go
pkg/cloud/aws/assets/deployment.yaml

Requirements to work:
----
Needs to additionally be merged:

Initial AWS CCM deployment using upstream image

---

cmd/cluster-cloud-controller-manager-operator/main.go
controllers/clusteroperator_controller.go
hack/example-images.json
manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
manifests/image-references

Reverts openshift/cluster-cloud-controller-manager-operator#30

Revert "Revert "Add images config map""

---

manifests/0000_26_cloud-controller-manager-operator_00_namespace.yaml
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/openstack/assets/deployment.yaml

In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

Add management workload annotations

---

pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/openstack/assets/deployment.yaml

Following proposal we need to run at least 2 replicas of CCM
controllers scheduled on different master nodes for HA: 
https://github.com/openshift/enhancements/pull/463/files#diff-3e0e2c48e70215076dfe36c13768a823ab7080d929d80292f37db2ef5a2121e8R123
Requires pieces from https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/15 to be merged first.

Add anti-affinity settings to preserve HA for CCM pods

---

pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/openstack/assets/deployment.yaml

OpenStack pod requests are inheriting upstream values: https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml#L57-L59
AWS manifests: https://github.com/kubernetes/cloud-provider-aws/blob/master/manifests/aws-cloud-controller-manager-daemonset.yaml#L35-L37
More precise values could only be determined after https://github.com/openshift/library-go/pull/895 and https://github.com/openshift/machine-config-operator/pull/2386 are merged.

Add missing requests to AWS and OpenStack CCM deployments

---

controllers/clusteroperator_controller.go
controllers/clusteroperator_controller_test.go
controllers/config.go
controllers/config_test.go
controllers/substitution.go
controllers/substitution_test.go

This PR allows operator to dynamically configure image in provisioned resources such as CCM Deployment. 
This is done based on assumption that every CCM controller will be in a named container containing `controller` substring in it's name. All those containers images will be managed by operator, others will remain unchanged from initial manifest.
Operator is now populating Namespace for each resource it provisions. Cluster-scoped resources are also getting this namespace value, which is ok as it is not accounted and is not stored by API server on apply. This allows two operators to manage equivalent set of resources in different namespaces without clashes.

Provider image substitution

---

controllers/clusteroperator_controller.go
manifests/0000_26_cloud-controller-manager-operator_12_clusteroperator.yaml

This will allow to collect the logs for must gather if operator does not come up and unblock upgrades until CVO fix will be issued. Operator later populates missing resources.

Bug 1957879: Pre-create relatedObjects in the cluster operator

---

pkg/cloud/aws/assets/deployment.yaml

Satisfy requirements of "[sig-arch] Managed cluster should ensure platform components have system-* priority class associated"
Full log: https://console.build01.ci.openshift.org/api/kubernetes/api/v1/namespaces/ci-op-6t1wq5k4/pods/e2e-aws-ccm-openshift-e2e-test/log?container=test
Increase weight on affinity settings to ensure the two pods are not scheduled on the same Node in edge cases.
Reasoning: 
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-pod-as-critical
OpenStack manifests have that same field. Cluster will not become healthy during install if those pods are not healthy. Not `system-node-critical` as provisioned Nodes could operate without these pods running.

Ensure priorityClass is set on AWS CCM

---

controllers/substitution.go
pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/openstack/assets/deployment.yaml

`cloud-controller-manager` is currently the only name in our image substitution pattern accepts as valid. All platform manifests should follow this naming if the image is expected to be substituted.

Ensure AWS and OpenStack CCM container names are fit for image substitution

---

cmd/cluster-cloud-controller-manager-operator/main.go
controllers/cache.go
controllers/clusteroperator_controller.go
controllers/clusteroperator_controller_test.go
controllers/config.go
controllers/config_test.go
controllers/status.go
controllers/status_test.go
controllers/suite_test.go
go.mod
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
vendor/k8s.io/client-go/testing/actions.go
vendor/k8s.io/client-go/testing/fake.go
vendor/k8s.io/client-go/testing/fixture.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go

Operator correctly reports degraded and available conditions during reconcile.
- Distribute methods into packages where they belong.
- Add events on resource updates, cluster operator changes.
- Report progressing condition on cluster upgrade or resources change.

Improve operator status management

---

Makefile

this removes the unused `operator` target in favor of `build` for all
targets.

update all target in makefile

---

pkg/cloud/common/_testdata/assets/deployment.yaml
pkg/cloud/common/sources.go
pkg/cloud/common/sources_test.go

Is seems a deployment without replicas is perfectly marshable to
daemonSet, this is a nature of parsing some byte stream to a compatible
resource holder.
cc @lobziik

Use strict yaml unmarshal to ensure partial type safety

---

pkg/cloud/aws/aws.go
pkg/cloud/aws/aws_test.go
pkg/cloud/aws/bootstrap/pod.yaml
pkg/cloud/cloud.go
pkg/cloud/cloud_test.go
pkg/cloud/common/sources.go
pkg/cloud/openstack/openstack.go

Following Pod will serve Node initialization during cluster bootstrap in AWS.
- Running only ` --controllers=cloud-node` as `cloud-node` controller contains node initialization parts we require in bootstrap.
```yaml
apiVersion: v1
kind: Pod
metadata:
name: aws-cloud-controller-manager
namespace: kube-system
spec:
priorityClassName: system-cluster-critical
containers:
- args:
- --cloud-provider=aws
- --use-service-account-credentials=false
- --controllers=cloud-node # run only cloud-node controller required to bootstrap master nodes
- --kubeconfig=/etc/kubernetes/secrets/kubeconfig
- --leader-elect=false
- -v=2
image: gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.19.0-alpha.1
imagePullPolicy: IfNotPresent
name: cloud-controller-manager
volumeMounts:
- mountPath: …
```

Implement bootstrap aws

---

manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml
manifests/image-references
pkg/config/config.go
pkg/config/config_test.go
pkg/substitution/substitution.go
pkg/substitution/substitution_test.go

Add azure images to images configmap and image-reference file

Add azure images

---

pkg/cloud/azure/azure.go
pkg/cloud/azure/azure_test.go
pkg/cloud/azure/bootstrap/pod.yaml
pkg/cloud/cloud.go
pkg/cloud/cloud_test.go

The PR would allow to create Azure static pod to bootstrap node. The pod would look like so:
```yaml
apiVersion: v1
kind: Pod
metadata:
name: azure-cloud-controller-manager
namespace: kube-system
spec:
priorityClassName: system-node-critical
hostNetwork: true
containers:
- name: cloud-controller-manager
image: mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.0.0
imagePullPolicy: IfNotPresent
command: ["cloud-controller-manager"]
args:
- --cloud-provider=azure
- --controllers=cloud-node # run cloud-node controller only for Node initialization
- --kubeconfig=/etc/kubernetes/secrets/kubeconfig
- --cloud-config=/etc/kubernetes/configs/cloud.conf # cloud config is generated by https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/55
- …
```

Add generation of azure static CCM pod to bootstrap

---

OWNERS

There is no such registered component as "cloud-controller-manager".
It should be:
component: "Cloud Compute"
subcomponent: "Cloud Controller Manager"

Update component name in Owners

---

pkg/substitution/substitution.go

This change add the object name to the logs produced when doing a
substitution on a Deployment or DaemonSet. The kind of the resource has
been removed from the formatted fields and added directly into the log
statement.
without this PR, the logs for this code look like this:
```
I0621 19:20:34.823544       1 substitution.go:24] Substituting "cloud-controller-manager" in "Deployment" with registry.ci.openshift.org/ocp/4.9-2021-06-19-105001@sha256:a86c73704f2709692a19d67b8eea82bcf8166f82334e659fbbe828be81e306d5
```
after this PR it would look like this
```
I0621 19:20:34.823544       1 substitution.go:24] Substituting "cloud-controller-manager" in Deployment "aws-cloud-controller-manager" with registry.ci.openshift.org/ocp/4.9-2021-06-19-105001@sha256:a86c73704f2709692a19d67b8eea82bcf8166f82 …
```

add object names to the substitution logs

---

pkg/substitution/substitution.go
pkg/substitution/substitution_test.go

This will add support for image substitution in static pod, used in render implementation.

[OCPCLOUD-1162] Implement image substitution for Pod and generalise the approach for other objects

---

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/cloud/aws/assets/deployment.yaml

Operator has to be able to start on master Nodes, when all of them are
marked as uninitialized. Additionally not-ready taint has NoSchedule
effect on Nodes when the deadlock happens.

Tolerate uninitialized taint in operator pods

---

docs/dev/cloud-provider-integration.md
docs/dev/hacking-guide.md
hack/example-images.json
manifests/0000_26_cloud-controller-manager-operator_01_images.configmap.yaml
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
manifests/image-references
pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/aws/bootstrap/pod.yaml
pkg/cloud/azure/bootstrap/pod.yaml
pkg/cloud/openstack/assets/deployment.yaml
pkg/controllers/clusteroperator_controller_test.go
pkg/controllers/fixtures/images.json

Instead of using images from third-party registries and our CI registry, it's better to provide links to upstream images from quay.io

Use upstream openshift images from quay.io

---

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/aws/bootstrap/pod.yaml
pkg/cloud/azure/bootstrap/pod.yaml
pkg/cloud/cloud_test.go
pkg/cloud/openstack/assets/deployment.yaml

As CNI relies on CMM to initialist the Node IP addresses. We must ensure  that CCCMO can set up and reconfigure if necesssary the CCM pods before  the CNO has been deployed and before the CNI initialises the Node.
To achieve this, we must tolerate the not-ready taint, use host networking and use the internal API Load Balancer instead of the API Service.
Full motivation for why we need to do this can be found in this doc (RH Internal) https://docs.google.com/document/d/1yAczhHNJ4rDqVFFvyi7AZ27DEQdvx8DmLNbavIjrjn0/edit?ts=60de093f

Run CCCMO and CCM components before CNI

---

manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml

Now CCCMO fails because it can list deployments in "openshift-config" and "openshift-config-managed" namespaces.
```txt
E0705 11:26:19.089134       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:241: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:openshift-cloud-controller-manager-operator:cluster-cloud-controller-manager" cannot list resource "deployments" in API group "apps" in the namespace "openshift-config"
```
To prevent this, we add required rules to "cluster-cloud-controller-manager" roles in the related namespaces.

Allow the operator to list deployments in config namespaces

---

manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml

The issue was found recently with OpenStack CCM:
https://github.com/kubernetes/cloud-provider-openstack/issues/1514
```txt
W0705 21:33:42.494088       1 client_builder_dynamic.go:207] get token failed: serviceaccounts "node-controller" is forbidden: User "system:serviceaccount:openshift-cloud-controller-manager:cloud-controller-manager" cannot create resource "serviceaccounts/token" in API group "" in the namespace "kube-system"
```
To fix it we need to add a rule that allows CCMs to create SA tokens:
https://github.com/kubernetes/cloud-provider-openstack/pull/1521

Allow CCMs to create serviceaccounts/token

---

pkg/cloud/openstack/assets/config.yaml
pkg/cloud/openstack/assets/deployment.yaml

After #76 `/etc/kubernetes` is a read-only fs, so we can't create folders there.
```txt
Normal   Pulled     0s (x3 over 24s)  kubelet            Container image "quay.io/openshift/origin-openstack-cloud-controller-manager:4.9" already present on machine
Warning  Failed     0s                kubelet            Error: container create failed: time="2021-07-05T13:36:15Z" level=error msg="container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting \"/var/lib/kubelet/pods/7b2ade72-eb8b-49be-8f33-ce8a9c43d7b3/volumes/kubernetes.io~secret/secret-occm\" to rootfs at \"/etc/kubernetes/secret\" caused: mkdir /var/lib/containers/storage/overlay/5f06245b3bfd93c0c9b446484b6a918d80e1e63fa06b6e8339f157ddf41e5357/merged/etc/kubernete …
```

Use /etc/openstack to mount the config and secrets

---

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/aws/bootstrap/pod.yaml
pkg/cloud/azure/bootstrap/pod.yaml
pkg/cloud/cloud_test.go
pkg/cloud/openstack/assets/deployment.yaml

Because we are now using the script to set the environment, args weren't being passed through correctly. To resolve that, lets just inline them and ensure that the args are always inlined going forward
CC @Fedosin As you found the issue in your testing

Inline container args into command

---

pkg/config/config.go
pkg/config/config_test.go
pkg/controllers/clusteroperator_controller.go
pkg/substitution/substitution.go
pkg/substitution/substitution_test.go

In case of Single Node deployments we need to create just one CCM replica, because there will be a port conflict if there are many
of them.
To do so we observe the Infrastructure resource to check what kind of control plane topology the cluster has. If it's `SingleReplicaTopologyMode` then the operator creates just one CCM replica.

Use just one CCM replica for Single Node deployments

---

docs/dev/cloud-provider-integration.md
pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/cloud_test.go
pkg/cloud/openstack/assets/deployment.yaml

If CCMs are deployed on the same node, only one can start successfully. Other are in CrashLoopBackOff with this error message:
```txt
error: failed to create listener: failed to listen on 127.0.0.1:10258: listen tcp 127.0.0.1:10258: bind: address already in use
```
```sh
$ oc get pod -n openshift-cloud-controller-manager -owide
NAME                                                  READY   STATUS             RESTARTS   AGE   IP             NODE                      NOMINATED NODE   READINESS GATES
openstack-cloud-controller-manager-7c7df77595-7w4v9   1/1     Running            10         30m   10.0.129.124   mfedosin-tb5dj-master-1   <none>           <none>
openstack-cloud-controller-manager-7c7df77595-xphlm   0/1     CrashLoopBackOff   6          30m   10.0.129.124 …
```

Prevent CCMs to be on the same node

---

Dockerfile
Makefile
cmd/cloud-config-sync-controller/main.go
manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/controllers/common_consts.go

- cloud config sync controller was extracted to separate binary
- redundant rbac perms was removed
- deployment manifest changes
- 'verify' was removed from build make target

Extract cloud config sync controller to separate binary

---

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/cloud_test.go
pkg/cloud/openstack/assets/deployment.yaml

This updates the init script that must be present on pods/containers to remove the legacy fallback. I've also added a note to the test that links to where the current solution was implemented in MCO. ie https://github.com/openshift/machine-config-operator/pull/2232

Update the container init script to not use the legacy workaround

---

manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml
pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
pkg/cloud/azure/azure.go
pkg/cloud/azure/azure_test.go
pkg/cloud/cloud.go
pkg/cloud/cloud_test.go
pkg/config/config.go
pkg/substitution/substitution.go
pkg/substitution/substitution_test.go

depends on https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/86

Azure CCM assets

---

Makefile
cmd/cluster-cloud-controller-manager-operator/main.go
pkg/controllers/suite_test.go

This commit enables `errcheck` linter for golangci-lint and additionally corrects all cases pointed out by the linter.

Enable errcheck linter

---

manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml
pkg/config/config.go
pkg/config/config_test.go
pkg/controllers/clusteroperator_controller.go
pkg/substitution/substitution.go
pkg/substitution/substitution_test.go

To conform with existing components within OpenShift, this commit allows the operator to watch for ClusterWideProxy configuration and inject the relevant environment variables into the containers for the CCMs.
This ensures that cloud provider traffic is routed via customers proxies as per the rest of the outbound traffic from the OpenShift components.

[OCPCLOUD-1202] Allow CCMs to observe cluster wide proxy

---

pkg/substitution/substitution.go
pkg/substitution/substitution_test.go

Since we removed "render" code, we don't work with plain pods anymore. It means that FillConfigValues from "substitute" should work with Deployments and DaemonSets only.
This commit removes the Pod case from the function, and also updates the tests accordingly.

Substitution module cleanup

---

pkg/cloud/azure/azure.go
pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml
pkg/cloud/azurestack/azurestack.go
pkg/cloud/azurestack/azurestack_test.go
pkg/cloud/cloud.go
pkg/cloud/cloud_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/controllers/clusteroperator_controller.go
pkg/controllers/clusteroperator_controller_test.go

There is plenty of changes between public Azure and Stack one. With current substitution approach it is not convenient to handle it. Extracted to separate module.

Azure Stack separate assets

---

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml
pkg/cloud/cloud_test.go
pkg/cloud/openstack/assets/deployment.yaml

Per the guidelines in https://github.com/openshift/enhancements/blob/master/dev-guide/host-port-registry.md, we should only be using defined ports when running on host network.
This implements the requirements of that guide based off of the ports registered in https://github.com/openshift/enhancements/pull/847
/hold until the registered ports are agreed upon

Bug 1985366: Use registered ports and ensure that ports are defined in pod specs

---

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml

Because we moved the strategy to `Recreate` in #108, the rollingUpdate field must be empty. If it is not empty, this prevents the upgrade from going through. This should force it to empty to allow the upgrade.

Bug 1999018: Ensure rollingUpdate strategy is cleared to allow upgrades

---

cmd/cloud-config-sync-controller/main.go
cmd/cluster-cloud-controller-manager-operator/main.go
go.mod
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/cloud_test.go
pkg/cloud/openstack/assets/deployment.yaml
pkg/util/durations.go
vendor/k8s.io/component-base/config/options/leaderelectionconfig.go
vendor/modules.txt

To ensure consistency with other components within OpenShift, this PR enforces (via unit tests) a consistent set of leader election flags which adhere to the guidelines set out in the conentions (https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#handling-kube-apiserver-disruption)

Bug 2000191: Ensure CCCMO and CCMs adheres to OpenShift recommended leader election

---

manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml

Theres a typo that means the added fields are actually being ignored
Edit: This also removes the `rollingUpdate: {}` as this was actually causing issues of its own. The rollingUpdate field is a pointer so specifying it as empty blocked the update.

Bug 1998466: Fix deployment strategy typo

---

manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml

IBM CCM has a load balancer service monitor that needs to get services in order
to properly monitor their overall health. It also needs to access cluster
configuration data via configmaps in the kube-system namespace. RBAC updates
for the former will likely always be required for the IBM CCM. The later could
be removed if the IBM CCM configuration was refactored.
Related: https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/97

Allow CCMs to get services and configmaps

---

pkg/cloud/cloud_test.go

While reviewing the alibaba introduction to CCCMO I realised we have this same list duplicated across 3 different test suites. The likelihood of them getting out of sync is very high as we add more platforms.
To make this less likely, I've moved the list into a function so that we just call the function to return all of the platforms across each of the tests that need this list.

Remove duplicated platform list in cloud tests

---

pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/cloud_test.go
pkg/cloud/ibm/assets/deployment.yaml
pkg/cloud/openstack/assets/deployment.yaml

The cloud-route controller is disabled and forced disabled across the board today in OpenShift. This used to be enforced by setting `allocate-node-cidrs=false` but this was removed in https://github.com/kubernetes/cloud-provider/commit/f9aa959a5054f6160c1f5a7577220fbd104cd9bf (Note this is still true with in-tree cloud providers, just out of tree this no longer works).
Now we must set `configure-cloud-routes=false` to ensure that the route controller is not started. This should be a simpler approach to ensure the route controller is forced off than forcing the use of the `--controllers=•,-route` style flags.

Bug 2001825: Enforce the cloud-route controller disabled across platforms

---

README.md

Add links to CCMs repos.
Change Azure ci status.

Update readme. Add links to CCMs repos.

---

Makefile
hack/verify-diff.sh

Now our targets just fix related issues in the code. For CI it means that it doesn't report any errors, as jobs always finish successfully.
This commit adds a script that checks the output of git diff command. If the diff is not empty, then the code has been modified, and therefore it has some errors.
Running this script in CI will force it to report real errors in the jobs logs.
Co-authored-by: Danil Grigorev <dgrigore@redhat.com>

Check diff after generate and vendor tasks

---

pkg/cloud/aws/assets/deployment.yaml
pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/cloud_test.go
pkg/cloud/openstack/assets/deployment.yaml

Manual cherry-pick of #120 
We must disable the route controller across platforms as it is not supported within OpenShift.

Bug 2004924: Enforce the cloud-route controller disabled across platforms

---

go.mod

Now the job is broken because "make verify-vendor" returns an error. This commit fixes the problem by updating go.mod file.
The code is automatically generated by `make vendor`.

Fix "vendor" job

---

manifests/0000_26_cloud-controller-manager-operator_00_namespace.yaml

Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-cloud-controller-manager-operator` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz

podsecurity: enforce privileged for openshift-cloud-controller-manager-operator namespace

---

manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-ibm.yaml

Minimize the IAM scope for the IBM Cloud CCM, based on required
resources and permissions.

Minimize IAM scope for IBM Cloud CredReqs

---

docs/dev/trusted_ca_bundle_sync.md
pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/cloud_config_sync_controller_test.go
pkg/controllers/common_consts.go
pkg/controllers/trusted_ca_bundle_controller.go
pkg/controllers/trusted_ca_bundle_controller_test.go
pkg/controllers/watch_predicates.go
pkg/util/trustbundle.go

Additional trusted CA from cloud-config should also be counted during
ccm-trusted-ca sync procedure. Due to OCP installer nuances,
'additionalTrustBundle' not always ends up in the proxy object.
For handling such situation this patch introduces support of 'ca-bundle.pem'
key in cloud-config. CA from there will be added to ccm-trusted-ca along with
additional CA bundle which reffered by proxy object.
For additional context see:
openshift/installer#5251 (comment)

Bug 2017565: [OCPCLOUD-1306] Add user defined trusted CA from cloud-config to ccm-trusted-ca bundle 

---

pkg/cloud/ibm/assets/deployment.yaml

--feature-gates=IPv6DualStack=false  is no longer a valid option in kube 1.23

Remove invalid feature-gate option from ccm deployment

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
vendor/modules.txt

This PR updates the library-go to support Power VS out-of-tree cloud providers

Bump library-go for support Power VS out-of-tree cloud providers

---

manifests/0000_26_cloud-controller-manager-operator_03_rbac_provider.yaml

This was raised by our product security team. Looking at the cloud-provider library, the only usage of PersistentVolume is a [labelling interface](https://github.com/kubernetes/cloud-provider/blob/d3ee5ab10d70e1f304b00c1e835000ccea6df1b4/cloud.go#L277-L279). This is implemented by some of the cloud providers (eg AWS, Azure and GCP) but not others (eg IBM). 
Having checked the `k8s.io/cloud-provider` repository and the providers for IBM, AWS, Azure and GCP, I can't see this being called anywhere, and as such, I'm pretty sure we don't need these permissions.

Remove unused PersistentVolume RBAC

---

manifests/0000_26_cloud-controller-manager-operator_15_credentialsrequest-ibm.yaml

Add IAM permissions for ResourceGroups to the IBM Cloud
CredentialsRequests, due to changes in requirements for the IBM
Cloud CCM.
Partial: https://bugzilla.redhat.com/show_bug.cgi?id=2019219

[Bug 2019219] IBMCloud: Add RG IAM permissions

---

pkg/cloud/ibm/assets/deployment.yaml
pkg/cloud/ibm/ibm.go

Power VS platform used IBM Cloud Provider and by default the ibm cloud services like IAM are accessed via private endpoint, This PR contains the changes to use Public endpoints for Power VS platform by setting up a environmental variable in deployment file.
Related to Enhancement:  [openshift/enhancements#736](https://github.com/openshift/enhancements/pull/736)
Earlier Power VS PR: https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/129

Added enablePublicEndpoint environmental variable to IBM Cloud deployment file

---

pkg/controllers/clusteroperator_controller.go
pkg/controllers/clusteroperator_controller_test.go
pkg/controllers/resourceapply/resourceapply.go
pkg/controllers/resourceapply/resourceapply_test.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/admissionregistration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
vendor/modules.txt

Currently the operator uses Server-Side Apply (SSA)[1] to manage its resources. Unfortunately, this approach has some drawbacks as it allows users to modify resources independently from the operator.
To prevent this behavior, this commit adds custom apply functions inspired by ones from resourseapply module in library-go[2].
[1] https://kubernetes.io/docs/reference/using-api/server-side-apply/
[2] https://github.com/openshift/library-go/tree/master/pkg/operator/resource/resourceapply

Get rid of server-side apply

---

pkg/cloud/openstack/assets/deployment.yaml

We are supposed to substitute the image based on the image references we are passed. This is implemented using templating in all of the other providers, but it was missed within OSP.
CC @mdbooth

Bug 2025884: Inject openstack CCM image within deployment template

---

pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/cloud_config_sync_controller_test.go

AWS does not use cloud config at all at the moment,
skip its sync for this platform

Skip cloud-config sync on aws platform

---

cmd/cluster-cloud-controller-manager-operator/main.go
cmd/config-sync-controllers/main.go
pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/cloud_config_sync_controller_test.go
pkg/controllers/clusteroperator_controller.go
pkg/controllers/clusteroperator_controller_test.go
pkg/controllers/status.go
pkg/controllers/status_test.go
pkg/controllers/trusted_ca_bundle_controller.go
pkg/controllers/trusted_ca_bundle_controller_test.go

This PR moves logic from ClusterOperatorReconciler related to the status management into its own type - ClusterOperatorStatus. It allows to reuse it in other controllers.

[OCPCLOUD-1307] Refactor CCCMO cluster-operator resource handling

---

pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/cloud_config_sync_controller_test.go

on baremetal there is no credential to sync from, this change allows
cccmo to skip syncing on baremetal. it also adds a test clause for
sync skipping on baremetal.

Bug 2033489: allow baremetal platform to skip syncing

---

pkg/controllers/cloud_config_sync_controller.go

Currently we have a list of platforms where cloud sync is not required. Unfortunately, if we add a platform where it's not required and it's not in the list, the operator fails to start, and the whole cluster is degraded.
It's better to create a list of the platform where the sync is necessary, and ignore the others.

Bug 2033489: Use a list of platforms where config sync is required

---

pkg/controllers/trusted_ca_bundle_controller_test.go

You should not use gomega assertions within async assertions as was previously done. This meant that the async assertions actually had nothing to assert against. A bug in gomega allowed the tests to pass though they shouldn't have done.

Bug 2032926: Fix CA bundle tests to use async assertions correctly

---

cmd/config-sync-controllers/main.go
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml

Disable redundant config-sync-controller metrics server,
change health check port from 9259 to 9260.
Reassign mistakenly exposed ports from config-sync-controller to operator.
Also need add 9260 port here: https://github.com/openshift/enhancements/blob/master/dev-guide/host-port-registry.md as localhost only
P.S https://github.com/openshift/enhancements/pull/997

Bug 2037680: Fix CCCMO metric ports configuration

---

manifests/image-references
pkg/cloud/alibaba/assets/cloud-controller-manager-deployment.yaml

The CCCMO must deploy images from the release payload and not directly from the quay repo

Bug 2047998: Alibaba should deploy image from release payload

---

manifests/image-references
pkg/cloud/alibaba/assets/cloud-controller-manager-deployment.yaml

Manual cherry-pick #167
The CCCMO must deploy images from the release payload and not directly from the quay repo

Bug 2048478: [release-4.10] Alibaba should deploy image from release payload

---

pkg/controllers/watch_predicates.go

To get whether a config map belongs to the openshift config namespace we need to call `GetNamespace` and not `GetName`.

Fix a typo in watch predicates

---

pkg/controllers/clusteroperator_controller.go
pkg/controllers/watch_predicates.go

CCM operator deploys required resources only if KCM doesn't own related controllers. To check it CCM operator looks for
CloudControllerOwner condition with false value on KCM CR in its cache.
Currently we don't watch KCM, and therefore this condition is not present in the cache.
To fix it, this commit adds KCM to the list of watched resources, so the manager will add updates to the cache.

Bug 2055723: start watching KubeControllerManager resource

---

cmd/cluster-cloud-controller-manager-operator/main.go
cmd/config-sync-controllers/main.go
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/controllers/status.go

We must ensure that the release version environment variable is observed in all controllers else the version reported by the clusteroperator will flap during execution

Bug 2059716: Ensure release version is injected into all controller status clients

---

cmd/config-sync-controllers/main.go

Follow up to #175, I missed this controller and only added the release version to one of the two controllers in this manager

Bug 2059716: Ensure release version is set on config sync controller

---

pkg/cloud/openstack/openstack.go
pkg/cloud/openstack/openstack_test.go

The managed config-map is often updated even when all the
keys have the correct value, this behaviour is caused
by the fact that the order of the iteration of config-map
keys not preserved when using golang Map, consequently the final
version of the config-map would be considered different
from the previous one, when shouldn't. This commit fixes
the issue by ensuring that the order of the keys is
preserved in the config-map.

OpenStack: ensure config-map is updated only when needed

---

manifests/0000_26_cloud-controller-manager-operator_04_rbac_provider_openstack.yaml

cloud-provider-openstack expects to be able to [add an annotation to a LoadBalancer](https://github.com/kubernetes/cloud-provider-openstack/blob/21ce6dd984e5599ba3c411c960acdbcf9b5dbf03/pkg/openstack/loadbalancer.go#L1907) and [loadbalancer reconcile fails attempting to patch](https://github.com/kubernetes/cloud-provider-openstack/blob/21ce6dd984e5599ba3c411c960acdbcf9b5dbf03/pkg/openstack/loadbalancer.go#L1783) if it cannot.
Code in CPO executed by the service-controller runs as `cloud-controller-manager` in the `kube-system` namespace, which is [a dynamically created but hardcoded service account used by occm](https://github.com/kubernetes/cloud-provider-openstack/blob/21ce6dd984e5599ba3c411c960acdbcf9b5dbf03/pkg/openstack/openstack.go#L173).

Bug 2074606: Allow OpenStack CCM to annotate Service objects

---

cmd/cluster-cloud-controller-manager-operator/main.go
cmd/config-sync-controllers/main.go
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml
pkg/controllers/status.go

Manual cherry-pick of #175 and #176
> We must ensure that the release version environment variable is observed in all controllers else the version reported by the clusteroperator will flap during execution

Bug 2079791: Ensure release version is injected into all controller status clients

---

pkg/cloud/powervs/assets/deployment.yaml

With the latet update to Power VS cloud provider, its no more accepting port as argument
```
Error: unknown flag: --port
```
also there is [change](https://github.com/Karthik-K-N/cloud-provider-powervs/blob/c22143b62aa5c2230c3da784905d2343b4c80319/ibm/ibm_vpc_cloud.go#L36-L35) in environmental variable used to set use public endpoints for VPC

Remove port argument and update enivronment variable name from powervs cloud provider deployment

---

cmd/config-sync-controllers/main.go
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml

Manual cherry pick of #164
deployment misconfiguration causes upgrade issues from 4.8 to 4.9
Disable redundant config-sync-controller metrics server,
change health check port from 9259 to 9260.
Reassign mistakenly exposed ports from config-sync-controller to operator.
(cherry picked from commit 07cc7d760ee3e0e17b41913185394b08d32c99a7)

[release-4.9] Bug 2064837: Fix CCCMO metric ports configuration

---

pkg/cloud/ibm/assets/deployment.yaml

For the IBM Cloud CCM deployment, remove the unsupported --port
argument.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2082687

Bug 2082687: IBMCloud: Remove CCM port argument

---

pkg/cloud/cloud_test.go

OpenShift enforces the `--use-service-account-credentials` flag on CCMs.
This commit adds a test that makes sure this is configured correctly on each cloud provider except `vSphere` platform.
On vSphere they changed the behavior from what they have in the in-tree cloud provider. Code in this CCM executed by the `service-controller` runs as `vsphere-cloud-controller-manager` in the `kube-system` namespace, which is [a dynamically created but hardcoded service account](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/cloudprovider/vsphere/cloud.go#L108). But in the in-tree cloud provider the client is called [vsphere-legacy-cloud-provider](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go#L278)

[OCPCLOUD-1541] Bug 2089334: Use service account credentials for all providers

---

pkg/controllers/clusteroperator_controller_test.go
pkg/controllers/resourceapply/resourceapply.go
pkg/controllers/resourceapply/resourceapply_test.go

Manually cherry-picked resourceapply related changes from
https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/174
Several commits from this patchset was cherry-picked and then squashed together.
Such changes introduces recreation logic for daemonsets/deployments in case if
selectors was changed. Also, this contains respective tests changes.
Commits which was using for prepare this patch:
e1f47b7cbc1d1e908dcf62e90698a474eb40b58d
1bf44f1801d1f33338e7f165b7029726fdfdefdc
d4b6c3fc13d897d7c5226434faeb80784a84ce6a
5b17fa28080d2c43a91de630dc3d1b6ae9625880
a4963609a29c2587ba05ae2b4e8c04b193f71267
9429f586f430d0c0a818798f15fcb224e61599a7
748843291e06cb7506935fda5038b227fac85b73

Bug 2099499: Backport resourceapply changes for being able to recreate daemonsets/deployments

---

go.mod
go.sum
vendor/modules.txt

Following on from #199, we force merged dependencies from a branch. This resets back to the updated library-go commit and removes the replace statement.
No diff to the vendor.

Reset Go mod after openstack library-go bump

---

manifests/0000_26_cloud-controller-manager-operator_00_namespace.yaml

All techpreview jobs are currently failing because of the new pod security admission policy checks. This should resolve the issue for now
```
ns/openshift-cloud-controller-manager replicaset/gcp-cloud-controller-manager-79c85fb79b - reason/FailedCreate (combined from similar events): Error creating: pods "gcp-cloud-controller-manager-79c85fb79b-kln2f" is forbidden: violates PodSecurity "restricted:latest": host namespaces (hostNetwork=true), hostPort (container "cloud-controller-manager" uses hostPort 10258), allowPrivilegeEscalation != false (container "cloud-controller-manager" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cloud-controller-manager" must set securityContext.capabilities.drop=["ALL"]), restricted volume types (volume …
```

CCM namespace should be labelled as privileged

---

cmd/cluster-cloud-controller-manager-operator/main.go
cmd/config-sync-controllers/main.go
pkg/restmapper/predicates.go
pkg/restmapper/restmapper.go
pkg/restmapper/restmapper_test.go

This PR introduces a custom rest mapper capable of filtering API groups during the discovery procedure based on passed predicates.
Currently, the default mapper makes a lot of requests to the API server which might cause pretty long controller startup and might lead to crashes in case of network issues or slow responsive apiserver.
This code might be removed when a truly lazy rest mapper will be introduced (https://github.com/kubernetes-sigs/controller-runtime/issues/1603), or similar group filtering functionality for the discovery will be implemented in the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime)

OCPBUGS-4074: Try to limit groups for the REST mapper discovery

---

pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/trusted_ca_bundle_controller.go

To prevent showing too many less important messages in the log we set the verbosity level for them to 1.
Here is an [example](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-cloud-controller-manager-operator/213/pull-ci-openshift-cluster-cloud-controller-manager-operator-master-e2e-gcp-ovn-ccm-install/1612583627818799104/artifacts/e2e-gcp-ovn-ccm-install/gather-extra/artifacts/pods/openshift-cloud-controller-manager-operator_cluster-cloud-controller-manager-operator-5547c7d677-t68hk_config-sync-controllers.log) of such messages.

Change verbosity level for some logs

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
vendor/modules.txt

This PR updates the library-go dependency to include [a bump to move the vSphere cloud provider to out-of-tree](https://github.com/openshift/library-go/pull/1451). Note this PR must be merged at the same time as a [PR to KCMO](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/687) making the same bump to avoid a build that contains only one of the two bumps.
Tested with [cluster bot](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-vsphere-modern/1612407690103885824)

[OCPCLOUD-1818] Update library-go dependency to move vSphere to out of tree

---

cmd/azure-config-credentials-injector/credentials_injector_test.go
cmd/azure-config-credentials-injector/main.go

Add `--disable-identity-extension-auth` cmdline option to set `"useManagedIdentityExtension"` to false, because the purpose of the injector is to inject username + password into `cloud.conf` and therefore we want to use that credentials when talking to the cloud. `"useManagedIdentityExtension: true"` would use identity of the Azure VM.
cc @openshift/storage @Fedosin @lobziik

OCPBUGS-6658: Clear useManagedIdentityExtension if it's set

---

pkg/cloud/vsphere/vsphere_config_transformer.go

Changes to the installer to GA zonal
always create at least one failuredomain.
If labels are set and the tag or tag
categories do not exist installation boostrap
fails. To support the legacy non-zonal install
labels will only be applied when the length of
failure domains is greater than one.

vSphere: If only one failuredomain do not config labels

---

pkg/controllers/clusteroperator_controller.go
pkg/controllers/clusteroperator_controller_test.go
pkg/controllers/resourceapply/config_hash.go
pkg/controllers/resourceapply/config_hash_test.go
pkg/controllers/resourceapply/resourceapply.go
pkg/controllers/resourceapply/resourceapply_test.go

Manual cherry pick from #227 
This PR does not contain commits which is not needed for OCP 4.12 or ain't entirely related to the bugfix.

[release-4.12] OCPBUGS-7884: Restart pods if related configuration was changed 

---

pkg/controllers/clusteroperator_controller.go

Operator should not provision anything in case if 'External' platform is encountered.

OCPCLOUD-1779: Prevent operator to provision operands if platform is set to 'External'

---

go.mod
go.sum
vendor/modules.txt

After the promotion of Azure and AWS to out of tree, we had to use a fork to make sure merges happened in the right timing. This resets the go.mod back to the master branch of library-go.

Reset library-go to openshift fork

---

pkg/controllers/clusteroperator_controller.go

Follow up for
- https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/230
After #230 merged, we encountered that there is no operator status reported to cluseroperator object.
This PR adds missed status reporting.

OCPCLOUD-1779, OCPBUGS-8694: Set missed operator status in case of the 'External' platform type encountered

---

pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/cloud_config_sync_controller_test.go
pkg/controllers/clusteroperator_controller.go
pkg/controllers/status.go

When upgrading from 4.12 to 4.13 on the nutanix platform, the cloud-conf configmap must be present to avoid a degradation. This change adds a check in the cloud_config_sync_controller reconcile to check the platform type and configmap existence, if it does not exist on nutanix then the upgradeable condition will be set to false.
ref: https://issues.redhat.com/browse/OCPBUGS-7898

OCPBUGS-7898: add a check for nutanix cloud conf map

---

pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml

This enables the feature flag created in https://github.com/openshift/cloud-provider-azure/pull/62
We need this to preserve the behaviour of applying beta topology labels which have not yet been removed by openshift

OCPBUGS-11284: Add beta topology labels flag to Azure cloud node manager

---

pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/cloud_config_sync_controller_test.go

to make the sync controller act more like the main operator controller, this PR adds the upgradeable condition as part of setting available status as ready. This is to alleviate a situation on platform none where the upgradeable status is not getting configured properly.

[release-4.12] OCPBUGS-13188: update config sync controller to add upgrade status

---

pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/status.go
pkg/controllers/status_test.go

this change adds a separate condition for the sync controller so that primary controller can more accurately detect when the sync controller wants to mark a blocked upgrade. Separating the upgradeable condition in this manner prevents the primary controller from becoming blocked if it goes non-upgradeable due to its own issues or degraded status.
added a unit test to check that the interaction between the config sync controller and the primary controller is working the way we want.

OCPBUGS-13862: add separate upgradeable condition for the sync controller

---

cmd/azure-config-credentials-injector/credentials_injector_test.go
cmd/azure-config-credentials-injector/main.go

In scope of [Azure workload identity feature](https://docs.google.com/document/d/18y0pq0Jq0AgvCymb-4dwso_pwEKbUeXyLFRDW_JwgBA/edit#) we need to extend injector to parse new configuration values.

CCO-324,CCO-325: add support for workload identity

---

pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/clusteroperator_controller.go
pkg/controllers/status.go
pkg/controllers/status_test.go
pkg/controllers/trusted_ca_bundle_controller.go

Alibaba clusters are TechPreviewNoUpgrade and should not be upgradeable.
This introduces an upgrade blocker via CCMO to prevent alibaba clusters upgrading.
The condition management in this operator sucks and needs refactoring, for now, I've made an overrides concept so that the top level operator can pass these overrides down. We should come up with a better way of doing this.

OCPBUGS-14425: Alibaba platforms should not be upgreadable

---

pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
pkg/cloud/cloud_test.go

Customers have the ability to taint nodes via MachineSets, when they do so, they can prevent the cloud-node-manager from being created on worker nodes. If they do this, then the providerID and uninitialized taint are not set and not removed. This means that pods cannot schedule on the nodes and they become wedged.
To enable wider usage of the taints feature via MachineSets, this PR moves the toleration to allow any NoSchedule taint. This should be sufficient for most use cases. I've deliberately not included NoExecute taints since I think it is valid to not run on a NoExecute for the node manager.

OCPBUGS-16690: Allow all NoSchedule taints for Azure CNM DaemonSet

---

pkg/cloud/openstack/openstack.go
pkg/cloud/openstack/openstack_test.go

Sharing LBs in cloud-provider-openstack can have unintended consequences for the user. In particular there are potential security risks as this easily allows you to "attach" your Service to a port on an already existing FIP. Moreover there are some logic problems in handling them and feature breaks assumption that a Service can only point to pods from the same namespace, potentially breaking multitenancy.
This commit makes sure that by default OpenShift is not allowing multiple Services to share an LB. Admin can override this by explicitly setting `[LoadBalancer]max-shared-lb` in the cloud provider configuration.

OpenStack: Set max-shared-lb to disable the feature

---

pkg/cloud/openstack/OWNERS

Seems like we were missing some team members from approvers. This commit adds the whole team.

OpenStack: Extend owners

---

pkg/cloud/openstack/openstack.go
pkg/cloud/openstack/openstack_test.go

`manage-security-groups` enables us to be more granular when allowing LB access to the cluster nodes. When enabled, CPO will create SGs dynamically for each of the LoadBalancer Services and will make sure only required NodePorts are opened on the nodes.
This also enables `loadBalancerSourceRanges` support for LBs created using OVN Octavia Provider.
This commit makes sure the option is enabled by default. Admin can override it by setting it to false manually.

OpenStack: Enable manage-security-groups by default

---

cmd/azure-config-credentials-injector/credentials_injector_test.go
cmd/azure-config-credentials-injector/main.go
manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml
pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
pkg/cloud/azure/azure.go
pkg/cloud/azure/azure_test.go
pkg/cloud/cloud_test.go

Modify CCM and Node Manager deployments to use the CCCMO's Azure credentials injector as an init-container to merge the provided CCO credentials secret with the `/etc/kube/cloud.conf` file used to configure [cloud-provider-azure](https://github.com/openshift/cloud-provider-azure) as used within CCM and the Node Manager. An existing example usage of the credentials injector init-container can be found within the [azure-file-csi-driver-operator](https://github.com/openshift/azure-file-csi-driver-operator/blob/066cdf4a57c08c047303d00ac8b6e777cf7a5ff9/assets/controller.yaml#L45-L86).
The CCO provided credentials secret will either contain credentials for client secret or Azure AD Workload Identity auth. Client secret is the existing default in "passthrough" credentials mode clusters. CCM and …

OCPCLOUD-2149: Azure: CCM and node manager to use provided credentials instead of MSI.

---

manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml

This PR moves the Azure credentials request to use fine grained permissions rather than a generic role.
i've manually tested this and can bring up an Azure workload identity cluster with this manually. CI is covering our existing cluster bring up.

OCPCLOUD-2013: Move Azure Credentials Request to custom role

---

pkg/controllers/clusteroperator_controller.go

When deleting the project of CCCMO, we get garbage in the status of the manager which doesn't tell the user what is actually wrong. With addition of the condition message, it should be clearer for the user what is actually wrong.

OCPBUGS-14718: Add message for CABundleControllerDegradedCondition error

---

pkg/cloud/vsphere/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/vsphere/vsphere_config_transformer.go
pkg/cloud/vsphere/vsphere_config_transformer_test.go

We have discovered that in dual-stack setups NodeAddresses field of
the instance metadata contains only IPv4 addresses for VMs that do have
both IPv4 and IPv6 addresses assigned (and detected by the VM agent).
It has been traced back to the function responsible for populating this
metadata field. We found out that for our configuration we always filter
only IPv4 addresses even if running in dual-stack. Reason for that is
that `IPFamilyPriority` has a value of `ipv4` even when running in a
dual-stack setup.
This causes an issue because this instance metadata is cross-checked
with addresses provided by the kubelet as part of the
`alpha.kubernetes.io/provided-node-ip` annotation. Without correct value
of `IPFamilyPriority` we are thus removing all the IPv6 addresses.
This PR takes advantage …

OCPBUGS-18641: Set dual-stack IPFamilyPriority for vSphere

---

manifests/0000_26_cloud-controller-manager-operator_04_rbac_provider_openstack.yaml

OpenStack keeps a separate SA definition for its CCM with a permission to patch Services. kubernetes/cloud-provider-openstack#2383 extends the needs to also be able to create events and this patch solves that.

OSASINFRA-3284: Add Events to OpenStack's RBAC

---

pkg/cloud/openstack/openstack.go
pkg/cloud/openstack/openstack_test.go

Kuryr is being removed from 4.15, this commit removes the Kuryr bits from the OpenStack's CCM config transformer.

OSASINFRA-3289: OpenStack: Remove Kuryr bits

---

pkg/cloud/vsphere/vsphere_config_transformer.go
pkg/cloud/vsphere/vsphere_config_transformer_test.go

In 428d639f0272c17b33058b994bd43104525d0205 we have added a support for correctly setting `IPFamilyPriority` and `ExcludeNetworkSubnetCIDR` when using dual-stack configuration. That commit however missed the configuration for IPv6-only setups and as a result those clusters are running with `IPv4` as a value of `IPFamilyPriority`.
This PR changes the logic so that we now cover settings for both IPv6-only and dual-stack configurations. There is no need for explicit handling of IPv4-only clusters as those work correctly today.
Fixes: OCPBUGS-23308
Relates-to: OCPBUGS-18641

OCPBUGS-23308: Set IPFamilyPriority and ExcludeNetworkSubnetCIDR for vSphere IPv6-only

---

manifests/0000_26_cloud-controller-manager-operator_05_metrics-service.yaml
manifests/0000_26_cloud-controller-manager-operator_06_kube-rbac-proxy-config.yaml
manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml

This is a PR to get feedback and run tests on my changes for [OCPCLOUD-2278](https://issues.redhat.com//browse/OCPCLOUD-2278) - will add a more in depth description once we're sure it works as expected.

OCPCLOUD-2278: Add kube-rbac-proxy container & ensure metrics are only available via HTTPS

---

README.md

Testing noop to rebuild based on errors we are seeing in [4.16.0-0.nightly-2023-12-08-191525](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.16.0-0.nightly/release/4.16.0-0.nightly-2023-12-08-191525)
panic: flag logtostderr set at /go/src/github.com/openshift/cluster-cloud-controller-manager-operator/cmd/cluster-cloud-controller-manager-operator/main.go:80 before being defined
[cluster-cloud-controller-manager-operator](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-sdn-upgrade/1733205727444471808/artifacts/e2e-aws-sdn-upgrade/gather-extra/artifacts/pods/openshift-cloud-controller-manager-operator_cluster-cloud-controller-manager-operator-77db9d5494-mdhzq_cluster-cloud-controller-manager.log …

trt-1382: test add space

---

manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml
pkg/cloud/cloud_test.go
pkg/cloud/gcp/assets/gcp-cloud-controller-manager-clusterrole.yaml
pkg/cloud/gcp/assets/gcp-cloud-controller-manager-clusterrolebinding.yaml
pkg/cloud/gcp/gcp.go
pkg/cloud/gcp/gcp_test.go

This change adds back the ClusterRole and ClusterRoleBinding removed in this PR [OCPBUGS-5825](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/778).
This is because it is still required at present.

OCPBUGS-5825: Adds GCP ClusterRole and ClusterRoleBinding

---

pkg/cloud/azure/azure.go
pkg/cloud/azure/azure_test.go
pkg/cloud/cloud.go
pkg/controllers/cloud_config_sync_controller_test.go

This adds a CloudConfigTransformer for Azure that will set the VMType to 'standard' if unset.
It also adds the functionality from the cluster-config-operator azure CloudConfigTransformer, as we can no longer rely on it by introducing this transformer.
See #291, OCPBUGS-25483 and OCPBUGS-20213 for more information.

OCPBUGS-25483: Adds CloudConfigTransformer for Azure

---

pkg/cloud/ibm/assets/deployment.yaml

Drop the bind-address argument for the IBM Cloud CCM, as it is not required for operation and due to changes in OCP 4.16, Kube 1.29, attempting to bind the host node IP to the pod no longer works.

OCPBUGS-25887: IBMCloud: Patch CCM for 4.16

---

pkg/cloud/gcp/assets/cloud-controller-manager.yaml

This should increase the reactiveness of the GCP service controller, meaning that creation and deletion of load balancers is quicker.
/hold
I would like to review the service controller implementation within GCP and run payload testing before we merge this

OCPBUGS-13106: Increase GCP Concurrent Service Syncs to 10

---

manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml
pkg/cloud/azure/assets/azure-cloud-controller-manager-clusterrole.yaml
pkg/cloud/azure/assets/azure-cloud-controller-manager-clusterrolebinding.yaml
pkg/cloud/azure/azure.go
pkg/cloud/azure/azure_test.go
pkg/cloud/cloud_test.go

While reviewing some logs from the attached bugs, I noticed that there were some endpointslices issues with the RBAC
```
I0202 03:17:24.210238       1 reflector.go:325] Listing and watching *v1.EndpointSlice from k8s.io/client-go/informers/factory.go:150
W0202 03:17:24.211504       1 reflector.go:535] k8s.io/client-go/informers/factory.go:150: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:openshift-cloud-controller-manager:cloud-controller-manager" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
E0202 03:17:24.211538       1 reflector.go:147] k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io …
```

OCPBUGS-29012: Add EndpointSlices permissions for Azure

---

pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml

The Auth provider in the CCM has changed in 4.16 and is now relying on a different field within the Azure config, `AADClientCertPath`. It is not clear to me if this is intentional or not.
The field in the config can be overridden by setting this environment variable. It appears that this will be an easier long term fix while we ascertain if the upstream change should be reverted.

OCPBUGS-29220: Set AZURE_FEDERATED_TOKEN_FILE on CCM container

---

pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml

This should increase the reactiveness of the Azure service controller, meaning that creation and deletion of load balancers is quicker.
/hold
I would like to review the service controller implementation within Azure and run payload testing before we merge this

OCPBUGS-29012: Increase Azure Concurrent Service Syncs to 10

---

manifests/0000_26_cloud-controller-manager-operator_04_rbac_provider_openstack.yaml

With new events being adding to cloud-provider-openstack it's now required to also allow patching events.

Bug OCPBUGS-29605: Allow to patch events in OpenStack RBAC

---

pkg/cloud/openstack/assets/deployment.yaml
pkg/cloud/openstack/openstack.go
pkg/cloud/openstack/openstack_test.go

By an terrible oversight, since the in-tree, OpenStack cloud provider was run without passing `--cluster-name` argument, meaning that it just used the default of "kubernetes" as the cluster name when constructing the names of the LB resources. Obviously this led to conflicts when there were multiple OCP clusters in a single OpenStack tenant and it's still a challenge for example for QE running tests on a single cloud.
This issue couldn't be fixed easily, because we haven't had an upgrade story solved. Now kubernetes/cloud-provider-openstack#2552 is an attempt to make CCM rename the LBs when the cluster-name is reconfigured. This should allow us to finally solve the name conflict issues.
This commit makes sure that CCMO deploys OpenStack CCM passing `--cluster-name`.

OCPBUGS-13680: Pass --cluster-name to OpenStack CCM

---

pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml

In our documentation, we instruct users to add a NoExecute taint for the node-role.kubernetes.io/infra key. This is not tolerated by the azure node managers and can cause a race condition when new nodes are added that can prevent the node manager from running on a new node.
This change updates the tolerations for azure and ash to allow the infra taint, and it also makes the ash permissions more tolerant (same as azure) to prevent future failures.

OCPBUGS-33405: update azure and ash tolerations on node manager

---

pkg/cloud/nutanix/assets/cloud-controller-manager-deployment.yaml

https://issues.redhat.com/browse/OCPBUGS-34689
Customer running Openshift on Nutanix AHV and their Tenable Security Scan reported the following vulnerability on the Nutanix Cloud Controller Manager Deployment. 
We can resolve it by adding the "--tls-cipher-suites" option to the cli in the nutanix-ccm deployment manifest.

OCPBUGS-34689: Nutanix CCM pods Cipher Suites vulnerability issue

---

pkg/cloud/cloud_test.go

This PR will bring the unit tests closer to the current master state. This includes updating the matchers for the deployment tolerations, and removing the benchmark tests.
this PR is needed by #353

OCPBUGS-35562: update unit tests [release-4.13]

---

pkg/cloud/powervs/assets/deployment.yaml

Remove the --bind-address to localhost as it makes the liveness test fail with the following error:
Liveness probe error: Get "https://192.168.169.11:10258/healthz": dial tcp 192.168.169.11:10258: connect: connection refused

OCPBUGS-35798: PowerVS: Remove bind address

---

Makefile

Demonstration of using new envtest-releases.yaml file in the API repo to source envtest utilities.

NO-JIRA: Update envtest configuration to new index format

---

cmd/cluster-cloud-controller-manager-operator/main.go
manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml
pkg/cloud/azure/assets/validating-admission-policy-binding.yaml
pkg/cloud/azure/assets/validating-admission-policy.yaml
pkg/cloud/azure/azure.go
pkg/cloud/azure/azure_test.go
pkg/cloud/cloud_test.go
pkg/controllers/resourceapply/resourceapply.go

This PR adds a policy for the Azure cloud node manager that prevents the node manager on one node, from applying updates to other Node objects. This mirrors the Kubelet node admission that prevents kubelets from updating each other.
This is not expected to cause any issues with the node manager as they should never be cross communicating anyway, but, does prevent escalation should the node manager service account become compromised.
It also includes a fix to the klog which I realised was missing (we have no logs on the CCMO in recent times)

OCPBUGS-22190: Add Node Admission restriction for Azure node Manager

---

cmd/cluster-cloud-controller-manager-operator/main.go
manifests/0000_26_cloud-controller-manager-operator_02_rbac_operator.yaml
pkg/cloud/azure/assets/azure-cloud-provider-role.yaml
pkg/cloud/azure/assets/azure-cloud-provider-rolebinding.yaml
pkg/cloud/azure/azure.go
pkg/cloud/azure/azure_test.go
pkg/cloud/cloud_test.go

The current rebase is failing on a [lack of permission](https://github.com/openshift/cloud-provider-azure/pull/127#issuecomment-2598187091) for a new lease that the Azure CCM is trying to leverage.
This role/rolebinding fills the gap in permissions.

OCPCLOUD-2844: Add role/binding for new Azure AKS lease

---

pkg/cloud/aws/assets/deployment.yaml

I recently update the AWS CCM to set the load balancer, cluster scoped health checks to port 10256 and /healthz. It turns out, that even though the tests looked good, this config change was not being consumed by the CCM. We did not even pass the configmap into the AWS CCM.
I've tested this manually and when configuring the below, I can now see that the configmap options are honoured, and the health checks appear as expected.

OCPCLOUD-2843: AWS CCM should be configured with the AWS cloud provider config

---

pkg/cloud/azure/assets/validating-admission-service-annotation-policy-binding.yaml
pkg/cloud/azure/assets/validating-admission-service-annotation-policy.yaml
pkg/cloud/azure/azure.go
pkg/cloud/azure/azure_test.go
pkg/cloud/cloud_test.go
pkg/cloud/gcp/assets/validating-admission-policy-binding.yaml
pkg/cloud/gcp/assets/validating-admission-policy.yaml
pkg/cloud/gcp/gcp.go
pkg/cloud/gcp/gcp_test.go

if the annotation `cloud.google.com/network-tier` was used in service resource and it is left without value or incorrect value(say xyz) , the service goes to `Pending` status with only warning 
`  Warning  SyncLoadBalancerFailed  1s (x3 over 17s)  service-controller  Error syncing load balancer: failed to ensure load balancer: unsupported network tier: "xyz"`
, to avoid that , added the VAP .

OCPBUGS-48481: annotation validation policy

---

cmd/azure-config-credentials-injector/credentials_injector_test.go
cmd/azure-config-credentials-injector/main.go
pkg/cloud/azure/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azure/assets/cloud-node-manager-daemonset.yaml
pkg/cloud/azurestack/assets/cloud-controller-manager-deployment.yaml
pkg/cloud/azurestack/assets/cloud-node-manager-daemonset.yaml

Based on discussion https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/380#issuecomment-2668448871  this pr will keep both the secret and environment variables methods, this pr need to be merged first, then openshift/csi-operator#357, then remove environment variables https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/380
Built image [build 4.18,openshift/cluster-cloud-controller-manager-operator#385](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1894239232529010688) and installed cluster on azure and ash, cluster install succeed.
Built image [build 4.18,openshift/cluster-cloud-controller-manager-operator#385, …

OCPBUGS-41827: update injector to support secret as well

---

pkg/cloud/azurestack/assets/azure-cloud-provider-role.yaml
pkg/cloud/azurestack/assets/azure-cloud-provider-rolebinding.yaml
pkg/cloud/azurestack/azurestack.go
pkg/cloud/azurestack/azurestack_test.go
pkg/cloud/cloud_test.go

This role was only added to Azure as a result cloud provider on AzureStackHub started failing due to not being able to acquire the lease.
This PR copies the role to be included on ASH as well.

OCPBUGS-54427: Add rbac leases rbac for cloud-provider on Azure stack hub

---

cmd/config-sync-controllers/main.go

- Switched klog textlogger to just plain klog
Other controller fixed here:
https://github.com/openshift/cluster-cloud-controller-manager-operator/commit/913d6d96df0a9a1572ab751305385dcd8dc13aff

OCPBUGS-56508: Fix config-sync-controller logging

---

manifests/0000_26_cloud-controller-manager-operator_10_networkpolicy-default-deny.yaml

CCM is using hostNetwork: true, so most NetworkPolicy functionality does not apply to it [OCPSTRAT-176](https://issues.redhat.com/browse/OCPSTRAT-176) only need to add one default deny all policy.
```
$ oc get deploy -n openshift-cloud-controller-manager-operator -o yaml | grep hostNetwork  
hostNetwork: true
$ oc get deploy -n openshift-cloud-controller-manager -o yaml | grep hostNetwork  
hostNetwork: true
```

OCPCLOUD-2978: add deny all network policy

---

manifests/0000_26_cloud-controller-manager-operator_05_metrics-service.yaml

Changed the service's selector label to `k8s-app=cloud-manager-operator` to ensure it matches the deployment’s [template label](https://github.com/openshift/cluster-cloud-controller-manager-operator/blob/5fc7a51c0cd1955c8e450a11a58d65b4823aa6a5/manifests/0000_26_cloud-controller-manager-operator_11_deployment.yaml#L25). This enables the service to correctly discover the pod and creates an EndpointSlice for port 9258, which is necessary for proper documentation created by the communication matrix (see further explanation described in the opened [bug](https://issues.redhat.com/browse/OCPBUGS-53300))

OCPBUGS-53300: Update service selector to match deployment label

---

pkg/cloud/aws/aws_config_transformer.go
pkg/cloud/aws/aws_config_transformer_test.go
pkg/cloud/cloud.go
pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/cloud_config_sync_controller_test.go

Prior to 4.14, OCP's installer did not provide any cloud configuration in the `Infrastructure` resource. This was ok because nothing relied on it.
However in 4.19, we introduced a hard requirement for the cloud configuration on AWS.
This change allows us to gracefully handle missing information in `Infrastructure` by providing a minimal default `cloud.conf` on AWS.

OCPBUGS-59251: Default cloud.conf if no configmap is found

---

cmd/config-sync-controllers/main.go
pkg/cloud/aws/aws_config_transformer.go
pkg/cloud/aws/aws_config_transformer_test.go
pkg/cloud/azure/azure.go
pkg/cloud/azure/azure_test.go
pkg/cloud/azurestack/azurestack.go
pkg/cloud/azurestack/azurestack_test.go
pkg/cloud/cloud.go
pkg/cloud/common/config.go
pkg/cloud/openstack/openstack.go
pkg/cloud/openstack/openstack_test.go
pkg/cloud/vsphere/vsphere_config_transformer.go
pkg/cloud/vsphere/vsphere_config_transformer_test.go
pkg/controllers/cloud_config_sync_controller.go
pkg/controllers/cloud_config_sync_controller_test.go

Introducing feature gate support to the cloudConfigTransformer of cloud-config sync controller, so we can ensure custom configuration depending of OCP feature gate.
The idea is to provide the interface to enable the CCM feature of default SG provisioning on NLBs, [SPLAT-2137](https://issues.redhat.com/browse/SPLAT-2137).
The feature gate will added to providers in follow up PRs, starting to AWS config transformer: https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/391/commits/c61b48dc1c87ad42b810b764743ca87e692c3e3f , related to https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/391
```diff
-func setOpenShiftDefaults(cfg *awsconfig.CloudConfig) {
+func setOpenShiftDefaults(cfg *awsconfig.CloudConfig, features featuregates.FeatureGate) {
if …
```

SPLAT-2341: Add feature gate support in the cloud-config sync controller

---

manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml

This PR adds missing permissions related to Private Link Service.
1. Microsoft.Network/privatelinkservices/write
- Code: pkg/provider/privatelinkservice/repo.go:93
- API: client.CreateOrUpdate(ctx, resourceGroup, *pls.Name, pls)
2. Microsoft.Network/privatelinkservices/read
- Code: Various PLS Get operations and cache management
3. Microsoft.Network/privatelinkservices/delete
- Code: pkg/provider/privatelinkservice/repo.go:109
- API: client.Delete(ctx, resourceGroup, plsName)
4. Microsoft.Network/virtualNetworks/subnets/write
- Code: pkg/provider/azure_privatelinkservice.go:232
- API: subnetRepo.CreateOrUpdate(ctx, rg, vnetName, subnetName, subnet)
- Purpose: Disable PrivateLinkServiceNetworkPolicies on subnet
5. Microsoft.Network/loadBalancers/loadBalancingRules/read
- Required for Azure …

OCPBUGS-54490: Add Azure permissions for Private Link Service operations

---

manifests/0000_26_cloud-controller-manager-operator_14_credentialsrequest-azure.yaml

This permission is required for the DeletePublicIP function in the
Azure Cloud Controller Manager to properly clean up orphaned public IP
addresses when LoadBalancer services are deleted.
Code location:
- File: pkg/provider/azure_publicip_repo.go:81
- Function: DeletePublicIP
- API call: NetworkClientFactory.GetPublicIPAddressClient().Delete()

OCPBUGS-60385: Add Microsoft.Network/publicIPAddresses/delete permission
